= Git

Для эмуляции работы команды, необходимо работать в паре.

* Выполнить в паре все *Specification of tasks* приведенные ниже.
* *Specification of task* представляет собой последовательность действий.
* Для удобства будет использоваться следующее именование:
** `(1)` - первый разработчик
** `(2)` - второй разработчик

== Precondition

* Настройте Git используя команды приведенные ниже, но со своими значениями:

[source, shell script]
----
git config --local user.email "your_email@example.com"
git config --local user.name "Firstname Lastname"
git config --local core.editor "nano -w"
----

== Specification of task 1

* (1) создает *public repository*.
* (1) и (2) делают его локальную копию (`git clone ${repository-link}`, где `${repository-link}` - ссылка для *repository*).
* (1) создаёт в локальном репозитории файл `.gitignore` со следующим содержимым:

[source,gitignore]
----
# IntelliJ IDEA files
.idea/
*.iml

# Git files
.gitconfig
----

* (1) добавляет файл в *staging area* (`git add ${pathfiles}`, где `${pathfiles}` - путь к файлам, которые необходимо добавить (через пробел)).
* (1) делает *commit* (`git commit -m "${commit-message}"`, где `${commit-message}` - сообщение для *commit*).
* (1) делает *push* всех изменений (`git push`).
* (2) скачивает изменения, произошедшие в *remote repository* (`git fetch`).
* (2) делает *merge* в *local repository* все изменения произошедшие в *remote repository* (`git merge`).

IMPORTANT: `git pull` ~ `git fetch` + `git merge`

* (2) создаёт в локальном репозитории структуру простейшего java-проекта (директория `src` и в ней класс `Main`).
* (2) добавляет файл в *staging area*.
* (2) делает *commit*.
* (2) делает *push* всех изменений.
* (1) скачивает изменения, произошедшие в *remote repository*.
* (1) делает *merge* в *local repository* все изменения произошедшие в *remote repository*.

NOTE: Результат: *local repository* у (1) и (2) должны быть идентичны.

== Specification of task 2

* (1) меняет класс `Main`.
* (1) делает *commit*.
* (1) делает *push*.
* (2) меняет те же самые строки в класс `Main`.
* (2) делает *commit*.
* (2) делает *pull*.

WARNING: При выполнении команды `pull` произойдет ошибка, так как возник *merge-conflicts*.

* (2) решает *merge-conflicts*.
* (2) делает *commit*.
* (2) делает *push*.
* (1) делает *pull*.

NOTE: Результат: *local repository* у (1) и (2) должны быть идентичны.

== Specification of task 3

* (2) создаёт *branch* с именем `second-branch` (`git branch ${branch-name}`, где `${branch-name}` - имя для *branch*).
* (2) переключается в `second-branch` *branch*  (`git checkout ${branch-name}`, где `${branch-name}` - имя нужного *branch*)
* (2) вносит изменения в класс `Main`.
* (2) делает *commit*.
* (2) делает *push*.
* (1) скачивает изменения, произошедшие в *remote repository*.
* (1) делает *merge* изменений из ветви `second-branch` в *branch* `master`.
* (1) решает *merge-conflicts*.
* (1) делает *commit*.
* (1) делает *push*.
* (2) переключается на `master`.
* (2) делает *pull*.

NOTE: Результат: *local repository* у (1) и (2) должны быть идентичны.

== Specification of task 4

* (1) создаёт *branch* с именем `pull-branch`.
* (1) вносит изменения в класс `Main`.
* (1) делает *commit*.
* (1) делает *push*.
* (1) создаёт *Merge Request*/*Pull Request* на *merge* ветки `pull-branch` в `master`.
* (2) одобряет *MR*/*PR*.
* (2) осуществляет *merge*.
* (1) и (2) переключаются на `master`.
* (1) и (2) делают *pull*.
* (2) создаёт *branch* с именем `many-commits`.
* (2) делает в ней несколько *commits*.
* (2) делает *push*.
* (1) скачивает изменения, произошедшие в *remote repository*.
* (1) затем открывает *log* для *commits* (`git log`).
* (1) делает *cherry-pick* в `master` любого *commit*, сделанного (2) (`git cherry-pick`).
* (1) делает *push*.
* (2) переключается на `master`.
* (2) делает *pull*.

NOTE: Результат: *local repository* у (1) и (2) должны быть идентичны.
